### ISSUE TITLE
Bibliotheksinformatik als tag ergänzen?

### ISSUE THREAD

**Issue by TobiasNx** [felixlohmeier/bibliotheks-und-archivinformatik#26]
Das Repo wird bei der Suche in Github nicht gefunden, wenn man nach "Bibliotheksinformatik" sucht . Wenn man Archivinformatik sucht, hingegen schon.

**Comment by felixlohmeier** [comment]
Danke für den Hinweis! Ich habe das Tag ergänzt (und "voyant" dafür geopfert, weil maximal 20 erlaubt sind)
